CREATE TABLE ESTUDIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    NOMBRE VARCHAR(500) NOT NULL, 
    TABLA VARCHAR(50) NOT NULL, 
    ORDENAR VARCHAR(50) NOT NULL, 
    AGRUPAR VARCHAR(50) NOT NULL, 
    OPERACION VARCHAR(50) NOT NULL,     
    TIPO_ORDEN VARCHAR(50) NOT NULL, 
    NUM_ELEMENTOS INTEGER NOT NULL, 
    PRIMARY KEY (ID)
);


CREATE TABLE ROL (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	NOMBRE VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY(ID)
);

CREATE TABLE CATEGORIA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CP VARCHAR(5) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CIUDAD VARCHAR(25) NOT NULL,
    PAIS VARCHAR(30) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    EDAD INTEGER NOT NULL,
    SEXO CHAR(1) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    ROL INTEGER NOT NULL DEFAULT 1,
  
	PRIMARY KEY (ID),
  FOREIGN KEY (ROL) REFERENCES ROL(ID) ON DELETE SET DEFAULT
);

CREATE TABLE PRODUCTO (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  VENDEDOR INTEGER NOT NULL,
    TITULO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(50),
    PRECIOSALIDA DOUBLE NOT NULL,
    URL_FOTO VARCHAR(200),
    MARCA VARCHAR(20), 
  	CATEGORIA INTEGER,
    FECHAINICIO DATE NOT NULL, 
  
	PRIMARY KEY (ID),
  FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE SET NULL,
  FOREIGN KEY (VENDEDOR) REFERENCES USUARIO(ID) ON DELETE CASCADE
);


CREATE TABLE PUJA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	COMPRADOR INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    ADJUDICADO BOOLEAN NOT NULL,
    PRECIO DOUBLE NOT NULL,
	PRODUCTO INTEGER NOT NULL,
  
	PRIMARY KEY(ID),
  FOREIGN KEY (COMPRADOR) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE
);


CREATE TABLE LISTA(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIAS_PREFERIDAS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	USUARIO INTEGER NOT NULL,
    CATEGORIA INTEGER NOT NULL, 
  
	PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE LISTAS_USUARIO (
		ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	USUARIO INTEGER NOT NULL,
    LISTA INTEGER NOT NULL, 

	PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  FOREIGN KEY (LISTA) REFERENCES LISTA(ID) ON DELETE CASCADE
);
CREATE TABLE FAVORITOS(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USUARIO INTEGER NOT NULL,
    PRODUCTO INTEGER NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE
);

INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('ypbsld');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('mwtonb');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('mxymim');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('fzpjgg');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('sxnppg');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('mhbnbi');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('respgp');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('xwbtlx');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('ywzqfl');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('pjiygw');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('rtgugd');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('ezlfry');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('bhtouf');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('yvyxho');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('zigujo');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('kocisq');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('qkvkut');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('bribzt');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('bnwlmi');
INSERT INTO CATEGORIA (NOMBRE) 
	VALUES ('xgopht');
	

INSERT INTO ROL (NOMBRE) 
	VALUES ('Usuario');
INSERT INTO ROL (NOMBRE) 
	VALUES ('Analista');
INSERT INTO ROL (NOMBRE) 
	VALUES ('Administrador');
	
	
	
INSERT INTO USUARIO (CP, NOMBRE, APELLIDOS, DIRECCION, CIUDAD, PAIS, TELEFONO, EMAIL, EDAD, SEXO, USERNAME, PASSWORD, ROL) 
	VALUES ('29004', 'Carlos', 'Ortega', 'Calle Amalia Heredia', 'Malaga', 'Spain', '676109629', 'carlosortch@gmail.com', 21, 'H', 'carlosortch', 'leonel10', 1);
INSERT INTO USUARIO (CP, NOMBRE, APELLIDOS, DIRECCION, CIUDAD, PAIS, TELEFONO, EMAIL, EDAD, SEXO, USERNAME, PASSWORD, ROL) 
	VALUES ('1000', 'a', 'a', 'a', 'a', 'Afganistan', '777777777', 'a@gmail.com', 20, 'H', 'a', 'a', 1);
INSERT INTO USUARIO (CP, NOMBRE, APELLIDOS, DIRECCION, CIUDAD, PAIS, TELEFONO, EMAIL, EDAD, SEXO, USERNAME, PASSWORD, ROL) 
	VALUES ('29650', 'Alfonso', 'Garcia Galvez', 'calle telera', 'malaga', 'Spain', '633771036', 'alf@gmail.com', 22, 'H', 'admin', 'admin', 4);
INSERT INTO USUARIO (CP, NOMBRE, APELLIDOS, DIRECCION, CIUDAD, PAIS, TELEFONO, EMAIL, EDAD, SEXO, USERNAME, PASSWORD, ROL) 
	VALUES ('29900', 'Manuel Cristóbal', 'Roldán Gómez', 'calle telera', 'malaga', 'Spain', '683551036', 'man@gmail.com', 20, 'H', 'man', 'man', 2);
INSERT INTO USUARIO (CP, NOMBRE, APELLIDOS, DIRECCION, CIUDAD, PAIS, TELEFONO, EMAIL, EDAD, SEXO, USERNAME, PASSWORD, ROL) 
	VALUES ('29004', 'sdf', 'fs', 'asfa', 'MÃ¡laga', 'Spain', '677889936', 'adkdks@gmail.com', 20, 'H', 'arroba', 'arroba', 1);




INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'lhaeetrx', 'pede libero', 32.2, 'http://dummyimage.com/223x100.png/5fa2dd/ffffff', 'Wordify', 16, '2022-02-08');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'hccgliap', 'vitae mattis', 978.66, 'http://dummyimage.com/110x100.png/dddddd/000000', 'Quimm', 14, '2021-08-16');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'tiuvktsv', 'id ligula', 464.84, 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 'Skimia', 16, '2022-05-13');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'wgtxxmct', 'praesent lectus', 656.57, 'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 'Izio', 15, '2022-02-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'krfolbka', 'tincidunt eu', 344.46, 'http://dummyimage.com/128x100.png/dddddd/000000', 'Tazzy', 17, '2022-02-23');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'sdkwqpcm', 'in faucibus', 490.66, 'http://dummyimage.com/209x100.png/ff4444/ffffff', 'Ooba', 6, '2022-01-04');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'mcegwduv', 'mattis odio', 997.76, 'http://dummyimage.com/180x100.png/cc0000/ffffff', 'Skippad', 6, '2021-08-15');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'xowimcmr', 'nunc rhoncus', 962.93, 'http://dummyimage.com/212x100.png/cc0000/ffffff', 'Flashset', 8, '2021-06-08');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'bempvqwq', 'risus praesent', 810.65, 'http://dummyimage.com/121x100.png/cc0000/ffffff', 'Mymm', 14, '2021-11-02');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ylsggjgd', 'dis parturient', 690.6, 'http://dummyimage.com/207x100.png/cc0000/ffffff', 'Gabspot', 18, '2022-04-06');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'uomksvtg', 'venenatis lacinia', 184.58, 'http://dummyimage.com/207x100.png/ff4444/ffffff', 'Twitterbeat', 12, '2021-12-05');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'dcyqzviv', 'est phasellus', 262.66, 'http://dummyimage.com/101x100.png/cc0000/ffffff', 'Wikizz', 11, '2022-01-23');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'xcofidnu', 'vestibulum sit', 402.34, 'http://dummyimage.com/144x100.png/ff4444/ffffff', 'Buzzbean', 5, '2021-07-16');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'kjmmxbiv', 'nulla sed', 567.5, 'http://dummyimage.com/217x100.png/5fa2dd/ffffff', 'Meeveo', 3, '2021-07-20');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'vdopvpiv', 'in hac', 923.72, 'http://dummyimage.com/185x100.png/ff4444/ffffff', 'Flashpoint', 15, '2022-04-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ltmuvfao', 'suspendisse ornare', 679.55, 'http://dummyimage.com/193x100.png/ff4444/ffffff', 'Voolith', 14, '2022-03-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'arldklho', 'eget tincidunt', 155.12, 'http://dummyimage.com/246x100.png/5fa2dd/ffffff', 'Realfire', 18, '2021-07-18');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'oscebobv', 'proin risus', 160.84, 'http://dummyimage.com/224x100.png/ff4444/ffffff', 'Shufflebeat', 7, '2021-12-09');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'mzexejpl', 'curabitur at', 539.22, 'http://dummyimage.com/224x100.png/dddddd/000000', 'Linkbridge', 18, '2022-05-07');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'vnmorxyb', 'nunc purus', 455.26, 'http://dummyimage.com/186x100.png/dddddd/000000', 'Kwideo', 16, '2021-06-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'kmbcjncz', 'justo aliquam', 616.98, 'http://dummyimage.com/178x100.png/ff4444/ffffff', 'Meevee', 3, '2021-07-26');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'xenqhomk', 'ultrices posuere', 568.96, 'http://dummyimage.com/179x100.png/dddddd/000000', 'Twitternation', 2, '2021-07-12');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ojkezbox', 'ac consequat', 314.76, 'http://dummyimage.com/112x100.png/cc0000/ffffff', 'Kamba', 2, '2022-01-17');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'mzraicdw', 'vel pede', 632.56, 'http://dummyimage.com/177x100.png/cc0000/ffffff', 'Meeveo', 5, '2022-04-20');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'ujmvmjse', 'neque libero', 447.54, 'http://dummyimage.com/224x100.png/ff4444/ffffff', 'Browsedrive', 15, '2022-03-20');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'rfdwttqr', 'sed vel', 654.49, 'http://dummyimage.com/179x100.png/dddddd/000000', 'Eadel', 14, '2021-06-22');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'mgjzlzsr', 'vivamus vel', 353.57, 'http://dummyimage.com/174x100.png/cc0000/ffffff', 'Shuffletag', 14, '2021-08-15');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'usafkfvj', 'amet eleifend', 939.49, 'http://dummyimage.com/241x100.png/ff4444/ffffff', 'Aimbu', 20, '2022-05-10');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'yyrnrloc', 'ipsum integer', 893.27, 'http://dummyimage.com/220x100.png/cc0000/ffffff', 'Skimia', 3, '2021-09-30');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'qyxxcubb', 'eget congue', 597.55, 'http://dummyimage.com/155x100.png/ff4444/ffffff', 'Mydo', 2, '2021-12-26');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'ihzqwmzs', 'odio condimentum', 865.21, 'http://dummyimage.com/223x100.png/cc0000/ffffff', 'Dynava', 18, '2022-03-04');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'zsdphtwq', 'in hac', 144.29, 'http://dummyimage.com/137x100.png/ff4444/ffffff', 'Yodoo', 15, '2022-04-22');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'lcsvdngo', 'diam cras', 336.82, 'http://dummyimage.com/107x100.png/dddddd/000000', 'Jatri', 2, '2022-03-28');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'vqfuuean', 'vivamus vestibulum', 160.64, 'http://dummyimage.com/245x100.png/dddddd/000000', 'Shuffledrive', 4, '2021-12-27');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'wnimagsf', 'nisl aenean', 853.6, 'http://dummyimage.com/245x100.png/cc0000/ffffff', 'Eazzy', 12, '2022-02-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'kudktapd', 'montes nascetur', 773.59, 'http://dummyimage.com/231x100.png/5fa2dd/ffffff', 'Flashdog', 18, '2021-08-10');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'pgaqihva', 'nulla nisl', 170.23, 'http://dummyimage.com/178x100.png/5fa2dd/ffffff', 'Vitz', 19, '2021-11-15');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'nuajjlzq', 'orci pede', 872.1, 'http://dummyimage.com/146x100.png/dddddd/000000', 'Agimba', 16, '2021-12-27');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'xspzrbfn', 'ut odio', 504.69, 'http://dummyimage.com/110x100.png/5fa2dd/ffffff', 'Shuffledrive', 13, '2022-04-16');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'jmaajccl', 'quisque porta', 455.93, 'http://dummyimage.com/169x100.png/5fa2dd/ffffff', 'Youbridge', 13, '2022-02-08');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'uyehctlb', 'venenatis non', 129.18, 'http://dummyimage.com/133x100.png/5fa2dd/ffffff', 'Agivu', 4, '2021-07-26');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'obsqruye', 'suspendisse potenti', 584.87, 'http://dummyimage.com/187x100.png/cc0000/ffffff', 'Ozu', 1, '2021-10-16');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'lsqjnzfk', 'metus vitae', 618.29, 'http://dummyimage.com/216x100.png/ff4444/ffffff', 'Innotype', 4, '2022-05-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'ndwojmze', 'a suscipit', 688.74, 'http://dummyimage.com/134x100.png/dddddd/000000', 'Minyx', 9, '2021-06-08');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'uxwgmeua', 'tellus nulla', 594.78, 'http://dummyimage.com/129x100.png/ff4444/ffffff', 'Tekfly', 18, '2022-04-02');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'tmmovvjg', 'duis aliquam', 815.34, 'http://dummyimage.com/193x100.png/5fa2dd/ffffff', 'Riffpedia', 5, '2021-05-30');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ysvkzmzt', 'amet consectetuer', 947.52, 'http://dummyimage.com/176x100.png/cc0000/ffffff', 'Skyvu', 8, '2021-11-04');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'qurpfcbs', 'interdum mauris', 307.08, 'http://dummyimage.com/217x100.png/ff4444/ffffff', 'Mynte', 17, '2021-12-29');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'fpqwuiki', 'nibh ligula', 690.76, 'http://dummyimage.com/247x100.png/ff4444/ffffff', 'Babbleblab', 10, '2021-12-28');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'kaxvwpst', 'eu orci', 897.82, 'http://dummyimage.com/157x100.png/cc0000/ffffff', 'Layo', 18, '2021-10-04');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'npwpwesd', 'in libero', 394.54, 'http://dummyimage.com/249x100.png/5fa2dd/ffffff', 'Zoomzone', 9, '2021-06-09');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'pfuyxvnp', 'at nunc', 752.89, 'http://dummyimage.com/135x100.png/5fa2dd/ffffff', 'Kaymbo', 12, '2021-10-02');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'aclkdheb', 'nulla ac', 880.0, 'http://dummyimage.com/167x100.png/ff4444/ffffff', 'Tagchat', 3, '2021-07-04');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'cvgjvrhm', 'sapien varius', 432.54, 'http://dummyimage.com/136x100.png/5fa2dd/ffffff', 'Quinu', 17, '2021-05-24');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'osyjewvu', 'viverra eget', 43.27, 'http://dummyimage.com/203x100.png/cc0000/ffffff', 'Pixoboo', 10, '2022-03-09');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'gzmbrgnk', 'in sagittis', 209.01, 'http://dummyimage.com/121x100.png/cc0000/ffffff', 'Browseblab', 14, '2021-06-22');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'vwgkzhde', 'lacinia erat', 153.25, 'http://dummyimage.com/129x100.png/5fa2dd/ffffff', 'Edgeify', 15, '2021-06-27');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'sskcctku', 'ligula in', 754.06, 'http://dummyimage.com/115x100.png/ff4444/ffffff', 'Ainyx', 15, '2021-11-02');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'unvhxhqf', 'platea dictumst', 102.44, 'http://dummyimage.com/235x100.png/ff4444/ffffff', 'Photobean', 8, '2021-08-24');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ikttrouv', 'sollicitudin mi', 735.86, 'http://dummyimage.com/137x100.png/5fa2dd/ffffff', 'Thoughtsphere', 8, '2021-10-17');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'wrpkjwys', 'mus vivamus', 872.4, 'http://dummyimage.com/133x100.png/cc0000/ffffff', 'Kazu', 1, '2022-05-13');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'kquseuiu', 'nonummy integer', 194.07, 'http://dummyimage.com/174x100.png/dddddd/000000', 'Eazzy', 3, '2022-03-25');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'xljvlvlv', 'sit amet', 453.65, 'http://dummyimage.com/155x100.png/cc0000/ffffff', 'Fliptune', 12, '2021-07-09');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ipmfzvek', 'odio justo', 659.1, 'http://dummyimage.com/226x100.png/ff4444/ffffff', 'Dynava', 4, '2022-02-06');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'uemaheny', 'ante vivamus', 527.21, 'http://dummyimage.com/146x100.png/cc0000/ffffff', 'Kimia', 11, '2021-12-20');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'bhwlraqm', 'faucibus orci', 421.65, 'http://dummyimage.com/185x100.png/5fa2dd/ffffff', 'Kamba', 5, '2021-07-17');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'bxifmwzj', 'quis justo', 322.09, 'http://dummyimage.com/162x100.png/5fa2dd/ffffff', 'Yodo', 8, '2022-03-06');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ymspvwkj', 'et ultrices', 890.37, 'http://dummyimage.com/188x100.png/ff4444/ffffff', 'Dabvine', 1, '2022-01-31');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'gmqwdjri', 'quis augue', 961.03, 'http://dummyimage.com/205x100.png/dddddd/000000', 'Riffpath', 10, '2021-06-17');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ofkayxoo', 'dictumst morbi', 234.91, 'http://dummyimage.com/229x100.png/cc0000/ffffff', 'Blogpad', 18, '2021-08-08');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'vkktlxtl', 'donec ut', 805.64, 'http://dummyimage.com/210x100.png/cc0000/ffffff', 'Camido', 15, '2021-11-30');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'gdtnskxz', 'turpis a', 579.55, 'http://dummyimage.com/120x100.png/ff4444/ffffff', 'Thoughtbridge', 14, '2021-12-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'djmyjqpr', 'hendrerit at', 252.91, 'http://dummyimage.com/165x100.png/ff4444/ffffff', 'Centidel', 20, '2022-01-17');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'kyrvnlpa', 'nisl aenean', 516.49, 'http://dummyimage.com/135x100.png/ff4444/ffffff', 'Vinder', 18, '2022-01-23');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'xhbsmeii', 'tincidunt ante', 928.79, 'http://dummyimage.com/207x100.png/cc0000/ffffff', 'Kazio', 19, '2021-05-19');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'rpiucnqs', 'erat vestibulum', 162.73, 'http://dummyimage.com/190x100.png/ff4444/ffffff', 'Minyx', 16, '2021-09-11');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'fjncmpeq', 'maecenas pulvinar', 583.63, 'http://dummyimage.com/178x100.png/dddddd/000000', 'Quatz', 14, '2021-07-02');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'rzjojpit', 'vitae mattis', 16.04, 'http://dummyimage.com/149x100.png/ff4444/ffffff', 'Voolia', 11, '2022-01-28');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'muewdyhc', 'est et', 198.44, 'http://dummyimage.com/190x100.png/cc0000/ffffff', 'Wordpedia', 14, '2021-09-06');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'ohiatuqp', 'et eros', 547.06, 'http://dummyimage.com/223x100.png/dddddd/000000', 'Shuffletag', 6, '2021-09-12');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'uagyrqfq', 'vitae mattis', 170.2, 'http://dummyimage.com/169x100.png/cc0000/ffffff', 'Photofeed', 5, '2022-04-24');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'kovzdpwl', 'tempus semper', 192.79, 'http://dummyimage.com/194x100.png/cc0000/ffffff', 'Wikizz', 7, '2022-04-22');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'lyfgracn', 'dui maecenas', 277.3, 'http://dummyimage.com/109x100.png/ff4444/ffffff', 'Vipe', 1, '2021-07-19');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'dabsmwap', 'id nisl', 344.68, 'http://dummyimage.com/137x100.png/cc0000/ffffff', 'Gabvine', 1, '2021-07-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'pmlxnfjx', 'fermentum justo', 606.8, 'http://dummyimage.com/183x100.png/dddddd/000000', 'Eamia', 5, '2021-09-21');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'ulzkpzjl', 'pede libero', 984.0, 'http://dummyimage.com/231x100.png/5fa2dd/ffffff', 'Yodo', 5, '2022-04-10');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'ydxgimux', 'nunc viverra', 418.57, 'http://dummyimage.com/113x100.png/5fa2dd/ffffff', 'Flipstorm', 8, '2021-12-03');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'tdljunvx', 'lacus morbi', 974.23, 'http://dummyimage.com/120x100.png/5fa2dd/ffffff', 'Devpulse', 13, '2022-03-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'vpfgnsfc', 'nascetur ridiculus', 647.02, 'http://dummyimage.com/209x100.png/ff4444/ffffff', 'Shuffledrive', 18, '2021-05-18');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'rxdkkhoq', 'ut dolor', 677.54, 'http://dummyimage.com/161x100.png/5fa2dd/ffffff', 'Avaveo', 20, '2021-11-24');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'dlxiadsm', 'odio in', 742.05, 'http://dummyimage.com/166x100.png/dddddd/000000', 'Bubbletube', 9, '2021-09-21');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'bxtksrfb', 'cras in', 604.53, 'http://dummyimage.com/200x100.png/cc0000/ffffff', 'Babbleblab', 2, '2021-10-23');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'pxvurqtu', 'sociis natoque', 245.69, 'http://dummyimage.com/177x100.png/5fa2dd/ffffff', 'Kazio', 18, '2021-07-17');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'rlomugld', 'at lorem', 118.84, 'http://dummyimage.com/135x100.png/cc0000/ffffff', 'Jetwire', 8, '2021-08-30');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'jbnpesjt', 'pellentesque volutpat', 783.84, 'http://dummyimage.com/249x100.png/cc0000/ffffff', 'Kanoodle', 3, '2021-07-31');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'evowzehd', 'curabitur in', 687.35, 'http://dummyimage.com/165x100.png/cc0000/ffffff', 'Oozz', 19, '2021-06-27');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'hlstxlxs', 'curae mauris', 437.11, 'http://dummyimage.com/235x100.png/cc0000/ffffff', 'Gigabox', 16, '2021-09-13');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (2, 'yqmtrilj', 'fusce lacus', 479.08, 'http://dummyimage.com/139x100.png/5fa2dd/ffffff', 'Fanoodle', 7, '2021-08-01');
INSERT INTO PRODUCTO (VENDEDOR, TITULO, DESCRIPCION, PRECIOSALIDA, URL_FOTO, MARCA, CATEGORIA, FECHAINICIO) 
	VALUES (1, 'ymrmrhmt', 'nec nisi', 836.72, 'http://dummyimage.com/121x100.png/dddddd/000000', 'Skaboo', 17, '2021-08-06'); 
