CREATE TABLE ESTUDIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(100),
	PRIMARY KEY(ID)
);

CREATE TABLE ROL (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	NOMBRE VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY(ID)
);

CREATE TABLE CATEGORIA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CP VARCHAR(5) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CIUDAD VARCHAR(25) NOT NULL,
    PAIS VARCHAR(30) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    EDAD INTEGER NOT NULL,
    SEXO CHAR(1) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    ROL INTEGER NOT NULL DEFAULT 1,
  
	PRIMARY KEY (ID),
  FOREIGN KEY (ROL) REFERENCES ROL(ID) ON DELETE SET DEFAULT
);

CREATE TABLE PRODUCTO (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  VENDEDOR INTEGER NOT NULL,
    TITULO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(50),
    PRECIOSALIDA DOUBLE NOT NULL,
    URL_FOTO VARCHAR(200),
    MARCA VARCHAR(20), 
  	CATEGORIA INTEGER,
    FECHAINICIO DATE NOT NULL, 
  
	PRIMARY KEY (ID),
  FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE SET NULL,
  FOREIGN KEY (VENDEDOR) REFERENCES USUARIO(ID) ON DELETE CASCADE
);


CREATE TABLE PUJA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	COMPRADOR INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    ADJUDICADO CHAR(1) NOT NULL,
    PRECIO DOUBLE NOT NULL,
	PRODUCTO INTEGER NOT NULL,
  
	PRIMARY KEY(ID),
  FOREIGN KEY (COMPRADOR) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE
);


CREATE TABLE LISTA(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIAS_PREFERIDAS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	USUARIO INTEGER NOT NULL,
    CATEGORIA INTEGER NOT NULL, 
  
	PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE LISTAS_USUARIO (
		ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  	USUARIO INTEGER NOT NULL,
    LISTA INTEGER NOT NULL, 

	PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
  FOREIGN KEY (LISTA) REFERENCES LISTA(ID) ON DELETE CASCADE
);